import Head from "next/head";
import App from "../packages/components/App";
import styles from "../styles/Home.module.css";
import Nav from "../packages/components/Nav";
import Footer from "../packages/components/Footer";

function createSquaresMatrix() {
  const squaresMatrix = [];
  for (let y = 4; y >= 0; y--) {
    for (let x = 0; x < 5; x++) {
      const squareObject = {
        coordinates: [x, y],
        id: x + y * 5,
        index: 5 * (4 - y) + x,
        neighborsIndex: {
          N: y + 1 <= 4 ? 5 * (4 - (y + 1)) + x : "",
          S: y - 1 >= 0 ? 5 * (4 - (y - 1)) + x : "",
          E: x + 1 <= 4 ? 5 * (4 - y) + (x + 1) : "",
          W: x - 1 >= 0 ? 5 * (4 - y) + (x - 1) : "",
        },
        occupied: false,
      };
      if (x == 0 && y == 0) {
        squareObject.occupied = true;
      }
      squaresMatrix.push(squareObject);
    }
  }
  return squaresMatrix;
}

const SQUARES_MATRIX = createSquaresMatrix();

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Robot Controller</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <main>
        <App squares={SQUARES_MATRIX} />
      </main>
      <Footer/>
    </div>
  );
}
