import Head from "next/head";
import Image from "next/image";
import { Box, Heading, Center, useColorModeValue } from "@chakra-ui/react";
import App from "../packages/components/App";
import styles from "../styles/Home.module.css";
import Nav from "../packages/components/Nav";

function createSquaresMatrix() {
  const squaresMatrix = [];
  for (let y = 4; y >= 0; y--) {
    for (let x = 0; x < 5; x++) {
      const squareObject = {
        coordinates: [x, y],
        id: x + y * 5,
        index: 5 * (4 - y) + x,
        neighborsIndex: {
          N: y + 1 <= 4 ? 5 * (4 - (y + 1)) + x : "",
          S: y - 1 >= 0 ? 5 * (4 - (y - 1)) + x : "",
          E: x + 1 <= 4 ? 5 * (4 - y) + (x + 1) : "",
          W: x - 1 >= 0 ? 5 * (4 - y) + (x - 1) : "",
        },
        occupied: false,
      };
      if (x == 0 && y == 0) {
        squareObject.occupied = true;
      }
      squaresMatrix.push(squareObject);
    }
  }
  return squaresMatrix;
}

const SQUARES_MATRIX = createSquaresMatrix();

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Robot Controller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <main>
        <App squares={SQUARES_MATRIX} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
